run:
  timeout: 3m
  tests: true
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gofumpt
    - gocritic
    - errcheck
    - unused
issues:
  exclude-rules:
    - path: _test\.go
      linters: [errcheck]
