run:
  timeout: 3m
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - gofumpt
    - gocritic
    - errcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters: [ errcheck ]
