name: CI

on:
  push:
    branches:
      - main
      - develop
      - 'feature/**'
      - 'test/**'
  pull_request:
    branches:
      - main
      - develop
  schedule:
    - cron: '0 3 * * *' # ежедневно в 03:00 UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true
          cache: false  # кешируем отдельным шагом

      - name: Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      # Docker есть на ubuntu-latest — testcontainers сам поднимет Postgres
      - name: Run tests (race)
        env:
          TESTCONTAINERS_RYUK_DISABLED: "false"
        run: |
          go mod tidy
          go test -race ./...
