name: Docker
on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
env:
  IMAGE_NAME: ghcr.io/${{ github.repository }}/bot

jobs:
  build_and_push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Version vars
        id: vars
        run: |
          echo "VERSION=$(git describe --tags --always --dirty)" >> $GITHUB_OUTPUT
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/setup-buildx-action@v3

      - name: Normalize image repo to lowercase (GHCR requirement)
        run: |
          echo "IMAGE_NAME_LOWER=$(echo '${{ env.IMAGE_NAME }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VERSION=${{ steps.vars.outputs.VERSION }}
            COMMIT=${{ steps.vars.outputs.COMMIT }}
          tags: |
            ${{ env.IMAGE_NAME_LOWER }}:${{ steps.vars.outputs.VERSION }}
            ${{ env.IMAGE_NAME_LOWER }}:sha-${{ steps.vars.outputs.COMMIT }}
            ${{ env.IMAGE_NAME_LOWER }}:latest
